services:
  # Web Service
  - type: web
    name: tutros
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install && npx prisma generate && npx prisma db push && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: tutros-db
          property: connectionString
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NODE_VERSION
        value: 20.11.0

databases:
  # PostgreSQL Database
  - name: tutros-db
    plan: free
    databaseName: tutros
    user: tutros
    region: singapore
